### ISSUE TITLE
TEP Workflow tracking via Github Issues

### ISSUE THREAD

**Issue by xchapter7x** [tektoncd/community#594]
### Feature request

__Given__ A tep-notifier custom task tracking PR events on the community repo (https://github.com/tektoncd/plumbing/pull/980)
__When__ a new TEP PR is created
__Then__ the task should automatically generate a Tracking issue in the community repo
    and reference the TEP PR in the comments
    and NOT hard link to the PR
    and contain the TEP id in the subject
    and have the tep status label applied
    and have the kind/tracking-issue label applied

#### Problem Statement:
As a Tekton Community Member there is little visibility into which TEPs are under active development, which PRs are linked to them and any discussions around implementation or functionality.

#### User Scenario:
As a Tekton Community Member 
I would like to be able to track the progress of a TEP through its phases of development
So that i can know what is being worked on, what is complete and generally what the state of TEPs are across the community.

**Comment by abayer** [comment]
Proposed workflow:

* A PR is opened to https://github.com/tektoncd/community to propose a new TEP.
  * The TEP automation bot/custom task extracts the TEP ID, title, and authors from the PR, and creates a tracking issue for the TEP in https://github.com/tektoncd/community, assigning it to the authors of the TEP, labeling it with `tep-status/new`, and including a link to the TEP PR.
* A PR to https://github.com/tektoncd/community is opened or edited, and that PR includes adding or making changes to an existing TEP markdown file.
  * If the TEP does not yet have a corresponding tracking issue, one is created as described above.
  * Otherwise, the description of the tracking issue is updated to include a link to the relevant PR.
* A PR to https://github.com/tektoncd/community is merged, and that PR includes adding or making changes to a TEP markdown file.
  * The bot/custom task again extracts the TEP ID, and any changes to title, authors, or status, and updates the relevant tracking issue accordingly. If the status is changing to a "terminal" status (i.e., `implemented`, `withdrawn`, or `replaced`), the tracking issue will be closed.
* A PR to one of the "project" repositories (i.e., https://github.com/tektoncd/pipeline, https://github.com/tektoncd/triggers, etc) is opened or edited.
  * If the PR references a TEP, either by ID, URL to the markdown file, or the tracking issue above:
    * A comment is added or updated (as needed) reminding that the TEP's status should be updated (see https://github.com/tektoncd/plumbing/pull/980).
    * The description of the tracking issue is updated to include a link to the "project" PR.

**Comment by xchapter7x** [comment]
| Sub-Feature | Feature Description | Owner | PR Link(s) | Started? (:white_large_square: / :white_check_mark: ) | Done? (:white_large_square: / :white_check_mark: ) |
| --------------- | --------------- | --------------- | --- | --- | --- | 
| A | <pr>A PR is opened to https://github.com/tektoncd/community to propose a new TEP. The TEP automation bot/custom task extracts the TEP ID, title, and authors from the PR, and creates a tracking issue for the TEP in https://github.com/tektoncd/community, assigning it to the authors of the TEP, labeling it with tep-status/new, and including a link to the TEP PR.</pr>  | @abayer  |  https://github.com/tektoncd/plumbing/pull/980  |  :white_large_square: | :white_large_square: |
| B | <pr>A PR to https://github.com/tektoncd/community is opened or edited, and that PR includes adding or making changes to an existing TEP markdown file. If the TEP does not yet have a corresponding tracking issue, one is created as described above. Otherwise, the description of the tracking issue is updated to include a link to the relevant PR.</pr>  |  |  | :white_large_square: | :white_large_square: |
| C | <pr>A PR to https://github.com/tektoncd/community is merged, and that PR includes adding or making changes to a TEP markdown file. The bot/custom task again extracts the TEP ID, and any changes to title, authors, or status, and updates the relevant tracking issue accordingly. If the status is changing to a "terminal" status (i.e., implemented, withdrawn, or replaced), the tracking issue will be closed.</pr>  |  |  |  :white_large_square: | :white_large_square: |
| D | <pr>A PR to one of the "project" repositories (i.e., https://github.com/tektoncd/pipeline, https://github.com/tektoncd/triggers, etc) is opened or edited. If the PR references a TEP, either by ID, URL to the markdown file, or the tracking issue above: A comment is added or updated (as needed) reminding that the TEP's status should be updated (see Add tep-notifier custom task to comment on PRs which should trigger TEP updates plumbing#980). The description of the tracking issue is updated to include a link to the "project" PR.</pr>  |  |  |  :white_large_square: | :white_large_square: |

**Comment by jerop** [comment]
@xchapter7x @abayer this is a great idea! created an issue to track TEP-0090 before the automation is available: https://github.com/tektoncd/community/issues/601 (based on the KEP issues template)

**Comment by xchapter7x** [comment]
@abayer 
what are your thoughts on a new feature here. 
When the tracking issue gets created, the robot adds said issue to this project https://github.com/orgs/tektoncd/projects/5

**Comment by abayer** [comment]
@xchapter7x Sounds good!

**Comment by abayer** [comment]
Actually, I wonder if a new project would make more sense - the workflows for TEP PRs and tracking issues wouldn't quite be the same thing. I need to dig further into the projects API/functionality...

**Comment by xchapter7x** [comment]
Agreed, the TEP PR (which is what is currently in the project linked above) is not the same as the Tracking Issue. 
However, the project's intent is to track the state of a given TEP through its lifecycle. Which overlaps with the intent of the Tracking Issue. It might make sense moving forward, rather than tracking a closed PR, to track the tracking issues in the project. 

thoughts?
